// Golden-vector regression for formula_preprocess_one — the PP-FormulaNet-S
// crop preprocess that was historically the CDM-0.27 root cause (a wrong
// resample / pad shifts every encoder input float and silently wrecks decode).
// A fixed deterministic BGR crop is frozen against the current correct output:
// sum/min/max plus sampled indices spanning the pad corners and the content
// band. Any change to the resample, normalization, gray conversion, or padding
// trips this immediately. Golden generated by running the current preprocess
// once and freezing it (see tools/ note in the PR).

#include <catch_amalgamated.hpp>

#include <cmath>
#include <cstdint>
#include <limits>
#include <vector>

#include "turbo_ocr/formula/ppformulanet/ppformulanet_preprocess.h"

using turbo_ocr::formula::formula_preprocess_one;
using turbo_ocr::formula::kFormulaInputSize;
using turbo_ocr::formula::kFormulaPadVal;

namespace {

// Deterministic synthetic crop: 18x11 BGR with per-channel variation so the
// gray-margin crop, AR-preserving resize+clamp, and center-pad all engage.
std::vector<uint8_t> make_crop(int W, int H) {
  std::vector<uint8_t> bgr(static_cast<std::size_t>(W) * H * 3);
  for (int y = 0; y < H; ++y)
    for (int x = 0; x < W; ++x) {
      uint8_t* p = bgr.data() + (static_cast<std::size_t>(y) * W + x) * 3;
      p[0] = static_cast<uint8_t>((x * 17 + y * 3) & 0xFF);
      p[1] = static_cast<uint8_t>((x * 5 + y * 29) & 0xFF);
      p[2] = static_cast<uint8_t>((x * 11 + y * 7) & 0xFF);
    }
  return bgr;
}

// Frozen golden (W=18, H=11, S=384).
constexpr double kGoldenSum = -433490.671810;
constexpr float  kGoldenMin = -4.563291f;
constexpr float  kGoldenMax = 0.610179f;

struct Sample { int idx; float val; };
constexpr Sample kGolden[] = {
    {0, -4.563291f}, {383, -4.563291f}, {147072, -4.563291f}, {147455, -4.563291f},
    {73920, -0.778142f}, {44220, -3.492012f}, {50020, -2.851790f}, {57800, -1.580575f},
    {69310, -1.047327f}, {77050, 0.068695f}, {88620, -2.422900f}, {54143, -0.917225f},
    {72960, -2.406451f}, {36960, -3.618392f}, {96130, -2.920880f}, {104060, -1.599934f},
};

}  // namespace

TEST_CASE("formula_preprocess_one matches the frozen golden vector",
          "[formula][preprocess]") {
  const int S = kFormulaInputSize;
  REQUIRE(S == 384);

  const auto bgr = make_crop(18, 11);
  std::vector<float> out(static_cast<std::size_t>(S) * S, 0.0f);
  formula_preprocess_one(bgr.data(), 18, 11, out.data());

  double sum = 0.0;
  float mn = std::numeric_limits<float>::infinity();
  float mx = -std::numeric_limits<float>::infinity();
  for (float v : out) {
    sum += v;
    mn = std::min(mn, v);
    mx = std::max(mx, v);
  }

  // Global checksum + range: a wrong resample/pad moves the sum by thousands.
  REQUIRE(sum == Catch::Approx(kGoldenSum).margin(50.0));
  REQUIRE(mn == Catch::Approx(kGoldenMin).margin(1e-4));
  REQUIRE(mx == Catch::Approx(kGoldenMax).margin(1e-3));

  // The four corners are the letterbox pad and must equal the normalized-zero
  // pad value exactly (structural, not just a sampled float).
  REQUIRE(out[0] == Catch::Approx(kFormulaPadVal).margin(1e-5));
  REQUIRE(out[static_cast<std::size_t>(S) * S - 1] ==
          Catch::Approx(kFormulaPadVal).margin(1e-5));

  // Per-index golden across pad corners and the content band.
  for (const auto& g : kGolden) {
    INFO("preprocess output diverged at index " << g.idx);
    REQUIRE(out[static_cast<std::size_t>(g.idx)] == Catch::Approx(g.val).margin(1e-3));
  }
}
