// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ocr.proto
#ifndef GRPC_ocr_2eproto__INCLUDED
#define GRPC_ocr_2eproto__INCLUDED

#include "ocr.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

namespace ocr {

// Error codes (HTTP parity)
// -------------------------
// Every non-OK gRPC response from this service carries a structured error
// code in the trailing metadata under the key "x-error-code". The value is
// the same string the HTTP API returns inside {"error":{"code":"..."}} so
// clients can branch on a single set of identifiers regardless of transport.
//
// Known codes:
//   LAYOUT_DISABLED, INVALID_PARAMETER, BASE64_DECODE_FAILED,
//   IMAGE_DECODE_FAILED, DIMENSIONS_TOO_LARGE, EMPTY_BATCH, MISSING_IMAGE,
//   MISSING_PDF, INVALID_DPI, INVALID_DIMENSIONS, BODY_SIZE_MISMATCH,
//   PDF_RENDER_FAILED, PDF_NOT_AVAILABLE, EMPTY_PDF, SERVER_BUSY,
//   INFERENCE_ERROR, NOT_READY, TABLE_BACKEND_DISABLED,
//   FORMULA_BACKEND_DISABLED, STRUCTURED_MODE_NO_STRUCTURE.
//
// The legacy grpc::StatusCode + status message remain primary for older
// clients; "x-error-code" is purely additive. Read it via
// ClientContext::GetServerTrailingMetadata() after the call completes.
class OCRService final {
 public:
  static constexpr char const* service_full_name() {
    return "ocr.OCRService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::ocr::OCRResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    virtual ::grpc::Status RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::ocr::OCRBatchResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>> AsyncRecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>>(AsyncRecognizeBatchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>> PrepareAsyncRecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>>(PrepareAsyncRecognizeBatchRaw(context, request, cq));
    }
    virtual ::grpc::Status RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::ocr::OCRPDFResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>> AsyncRecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>>(AsyncRecognizePDFRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>> PrepareAsyncRecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>>(PrepareAsyncRecognizePDFRaw(context, request, cq));
    }
    virtual ::grpc::Status Health(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::ocr::HealthResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>* AsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRBatchResponse>* PrepareAsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>* AsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::OCRPDFResponse>* PrepareAsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::ocr::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::ocr::OCRResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>> AsyncRecognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>>(AsyncRecognizeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>> PrepareAsyncRecognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>>(PrepareAsyncRecognizeRaw(context, request, cq));
    }
    ::grpc::Status RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::ocr::OCRBatchResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>> AsyncRecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>>(AsyncRecognizeBatchRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>> PrepareAsyncRecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>>(PrepareAsyncRecognizeBatchRaw(context, request, cq));
    }
    ::grpc::Status RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::ocr::OCRPDFResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>> AsyncRecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>>(AsyncRecognizePDFRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>> PrepareAsyncRecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>>(PrepareAsyncRecognizePDFRaw(context, request, cq));
    }
    ::grpc::Status Health(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::ocr::HealthResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>> AsyncHealth(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>>(AsyncHealthRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>> PrepareAsyncHealth(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>>(PrepareAsyncHealthRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, std::function<void(::grpc::Status)>) override;
      void Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, std::function<void(::grpc::Status)>) override;
      void RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, std::function<void(::grpc::Status)>) override;
      void RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, std::function<void(::grpc::Status)>) override;
      void Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>* AsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>* PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>* AsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>* PrepareAsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>* AsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>* PrepareAsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>* AsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>* PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Recognize_;
    const ::grpc::internal::RpcMethod rpcmethod_RecognizeBatch_;
    const ::grpc::internal::RpcMethod rpcmethod_RecognizePDF_;
    const ::grpc::internal::RpcMethod rpcmethod_Health_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Recognize(::grpc::ServerContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response);
    virtual ::grpc::Status RecognizeBatch(::grpc::ServerContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response);
    virtual ::grpc::Status RecognizePDF(::grpc::ServerContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response);
    virtual ::grpc::Status Health(::grpc::ServerContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Recognize() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::ocr::OCRRequest* request, ::grpc::ServerAsyncResponseWriter< ::ocr::OCRResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBatch(::grpc::ServerContext* context, ::ocr::OCRBatchRequest* request, ::grpc::ServerAsyncResponseWriter< ::ocr::OCRBatchResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizePDF(::grpc::ServerContext* context, ::ocr::OCRPDFRequest* request, ::grpc::ServerAsyncResponseWriter< ::ocr::OCRPDFResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Health() {
      ::grpc::Service::MarkMethodAsync(3);
    }
    ~WithAsyncMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::ocr::HealthRequest* request, ::grpc::ServerAsyncResponseWriter< ::ocr::HealthResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Recognize<WithAsyncMethod_RecognizeBatch<WithAsyncMethod_RecognizePDF<WithAsyncMethod_Health<Service > > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Recognize() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::ocr::OCRRequest, ::ocr::OCRResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response) { return this->Recognize(context, request, response); }));}
    void SetMessageAllocatorFor_Recognize(
        ::grpc::MessageAllocator< ::ocr::OCRRequest, ::ocr::OCRResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ocr::OCRRequest, ::ocr::OCRResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response) { return this->RecognizeBatch(context, request, response); }));}
    void SetMessageAllocatorFor_RecognizeBatch(
        ::grpc::MessageAllocator< ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecognizeBatch(
      ::grpc::CallbackServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response) { return this->RecognizePDF(context, request, response); }));}
    void SetMessageAllocatorFor_RecognizePDF(
        ::grpc::MessageAllocator< ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecognizePDF(
      ::grpc::CallbackServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Health() {
      ::grpc::Service::MarkMethodCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::ocr::HealthRequest, ::ocr::HealthResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response) { return this->Health(context, request, response); }));}
    void SetMessageAllocatorFor_Health(
        ::grpc::MessageAllocator< ::ocr::HealthRequest, ::ocr::HealthResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(3);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::ocr::HealthRequest, ::ocr::HealthResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_Recognize<WithCallbackMethod_RecognizeBatch<WithCallbackMethod_RecognizePDF<WithCallbackMethod_Health<Service > > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Recognize() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Health() {
      ::grpc::Service::MarkMethodGeneric(3);
    }
    ~WithGenericMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Recognize() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognize(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizeBatch(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognizePDF(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Health() {
      ::grpc::Service::MarkMethodRaw(3);
    }
    ~WithRawMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHealth(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(3, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Recognize() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Recognize(context, request, response); }));
    }
    ~WithRawCallbackMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Recognize(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecognizeBatch(context, request, response); }));
    }
    ~WithRawCallbackMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecognizeBatch(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->RecognizePDF(context, request, response); }));
    }
    ~WithRawCallbackMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* RecognizePDF(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Health() {
      ::grpc::Service::MarkMethodRawCallback(3,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Health(context, request, response); }));
    }
    ~WithRawCallbackMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Health(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recognize : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Recognize() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ocr::OCRRequest, ::ocr::OCRResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ocr::OCRRequest, ::ocr::OCRResponse>* streamer) {
                       return this->StreamedRecognize(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Recognize() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recognize(::grpc::ServerContext* /*context*/, const ::ocr::OCRRequest* /*request*/, ::ocr::OCRResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognize(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ocr::OCRRequest,::ocr::OCRResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecognizeBatch : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecognizeBatch() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse>* streamer) {
                       return this->StreamedRecognizeBatch(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecognizeBatch() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecognizeBatch(::grpc::ServerContext* /*context*/, const ::ocr::OCRBatchRequest* /*request*/, ::ocr::OCRBatchResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognizeBatch(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ocr::OCRBatchRequest,::ocr::OCRBatchResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_RecognizePDF : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_RecognizePDF() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse>* streamer) {
                       return this->StreamedRecognizePDF(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_RecognizePDF() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status RecognizePDF(::grpc::ServerContext* /*context*/, const ::ocr::OCRPDFRequest* /*request*/, ::ocr::OCRPDFResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognizePDF(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ocr::OCRPDFRequest,::ocr::OCRPDFResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Health : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Health() {
      ::grpc::Service::MarkMethodStreamed(3,
        new ::grpc::internal::StreamedUnaryHandler<
          ::ocr::HealthRequest, ::ocr::HealthResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::ocr::HealthRequest, ::ocr::HealthResponse>* streamer) {
                       return this->StreamedHealth(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Health() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Health(::grpc::ServerContext* /*context*/, const ::ocr::HealthRequest* /*request*/, ::ocr::HealthResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHealth(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::ocr::HealthRequest,::ocr::HealthResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Recognize<WithStreamedUnaryMethod_RecognizeBatch<WithStreamedUnaryMethod_RecognizePDF<WithStreamedUnaryMethod_Health<Service > > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Recognize<WithStreamedUnaryMethod_RecognizeBatch<WithStreamedUnaryMethod_RecognizePDF<WithStreamedUnaryMethod_Health<Service > > > > StreamedService;
};

}  // namespace ocr


#include <grpcpp/ports_undef.inc>
#endif  // GRPC_ocr_2eproto__INCLUDED
