// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: ocr.proto

#include "ocr.pb.h"
#include "ocr.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>
namespace ocr {

static const char* OCRService_method_names[] = {
  "/ocr.OCRService/Recognize",
  "/ocr.OCRService/RecognizeBatch",
  "/ocr.OCRService/RecognizePDF",
  "/ocr.OCRService/Health",
};

std::unique_ptr< OCRService::Stub> OCRService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< OCRService::Stub> stub(new OCRService::Stub(channel, options));
  return stub;
}

OCRService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Recognize_(OCRService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RecognizeBatch_(OCRService_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_RecognizePDF_(OCRService_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Health_(OCRService_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status OCRService::Stub::Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::ocr::OCRResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ocr::OCRRequest, ::ocr::OCRResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Recognize_, context, request, response);
}

void OCRService::Stub::async::Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ocr::OCRRequest, ::ocr::OCRResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, std::move(f));
}

void OCRService::Stub::async::Recognize(::grpc::ClientContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Recognize_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>* OCRService::Stub::PrepareAsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ocr::OCRResponse, ::ocr::OCRRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Recognize_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRResponse>* OCRService::Stub::AsyncRecognizeRaw(::grpc::ClientContext* context, const ::ocr::OCRRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecognizeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OCRService::Stub::RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::ocr::OCRBatchResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RecognizeBatch_, context, request, response);
}

void OCRService::Stub::async::RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecognizeBatch_, context, request, response, std::move(f));
}

void OCRService::Stub::async::RecognizeBatch(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecognizeBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>* OCRService::Stub::PrepareAsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ocr::OCRBatchResponse, ::ocr::OCRBatchRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RecognizeBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRBatchResponse>* OCRService::Stub::AsyncRecognizeBatchRaw(::grpc::ClientContext* context, const ::ocr::OCRBatchRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecognizeBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OCRService::Stub::RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::ocr::OCRPDFResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_RecognizePDF_, context, request, response);
}

void OCRService::Stub::async::RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecognizePDF_, context, request, response, std::move(f));
}

void OCRService::Stub::async::RecognizePDF(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_RecognizePDF_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>* OCRService::Stub::PrepareAsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ocr::OCRPDFResponse, ::ocr::OCRPDFRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_RecognizePDF_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ocr::OCRPDFResponse>* OCRService::Stub::AsyncRecognizePDFRaw(::grpc::ClientContext* context, const ::ocr::OCRPDFRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncRecognizePDFRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status OCRService::Stub::Health(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::ocr::HealthResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::ocr::HealthRequest, ::ocr::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Health_, context, request, response);
}

void OCRService::Stub::async::Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::ocr::HealthRequest, ::ocr::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, std::move(f));
}

void OCRService::Stub::async::Health(::grpc::ClientContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Health_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>* OCRService::Stub::PrepareAsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::ocr::HealthResponse, ::ocr::HealthRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Health_, context, request);
}

::grpc::ClientAsyncResponseReader< ::ocr::HealthResponse>* OCRService::Stub::AsyncHealthRaw(::grpc::ClientContext* context, const ::ocr::HealthRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncHealthRaw(context, request, cq);
  result->StartCall();
  return result;
}

OCRService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OCRService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OCRService::Service, ::ocr::OCRRequest, ::ocr::OCRResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OCRService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ocr::OCRRequest* req,
             ::ocr::OCRResponse* resp) {
               return service->Recognize(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OCRService_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OCRService::Service, ::ocr::OCRBatchRequest, ::ocr::OCRBatchResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OCRService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ocr::OCRBatchRequest* req,
             ::ocr::OCRBatchResponse* resp) {
               return service->RecognizeBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OCRService_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OCRService::Service, ::ocr::OCRPDFRequest, ::ocr::OCRPDFResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OCRService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ocr::OCRPDFRequest* req,
             ::ocr::OCRPDFResponse* resp) {
               return service->RecognizePDF(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      OCRService_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< OCRService::Service, ::ocr::HealthRequest, ::ocr::HealthResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](OCRService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::ocr::HealthRequest* req,
             ::ocr::HealthResponse* resp) {
               return service->Health(ctx, req, resp);
             }, this)));
}

OCRService::Service::~Service() {
}

::grpc::Status OCRService::Service::Recognize(::grpc::ServerContext* context, const ::ocr::OCRRequest* request, ::ocr::OCRResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OCRService::Service::RecognizeBatch(::grpc::ServerContext* context, const ::ocr::OCRBatchRequest* request, ::ocr::OCRBatchResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OCRService::Service::RecognizePDF(::grpc::ServerContext* context, const ::ocr::OCRPDFRequest* request, ::ocr::OCRPDFResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status OCRService::Service::Health(::grpc::ServerContext* context, const ::ocr::HealthRequest* request, ::ocr::HealthResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace ocr
#include <grpcpp/ports_undef.inc>

