"""Edge-case / outlier integration tests across all endpoints.

Uses fixtures generated by tests/fixtures/generate_edge_cases.py.
Assertions focus on crash-freeness, status codes, and schema shape —
NOT accuracy (edge cases intentionally have no ground truth).
"""

import pytest
import requests


# --- helpers ---------------------------------------------------------------

def _post_raw(server_url, data, content_type="image/png", timeout=30):
    return requests.post(
        f"{server_url}/ocr/raw",
        data=data,
        headers={"Content-Type": content_type},
        timeout=timeout,
    )


def _post_pdf(server_url, data, mode="ocr", timeout=120):
    return requests.post(
        f"{server_url}/ocr/pdf?mode={mode}",
        data=data,
        headers={"Content-Type": "application/pdf"},
        timeout=timeout,
    )


def _post_pixels(server_url, data, w, h, ch, timeout=10):
    return requests.post(
        f"{server_url}/ocr/pixels",
        data=data,
        headers={
            "X-Width": str(w),
            "X-Height": str(h),
            "X-Channels": str(ch),
        },
        timeout=timeout,
    )


# --- zero-byte / empty bodies ---------------------------------------------

class TestZeroByte:
    def test_raw_zero_byte(self, server_url, edge_cases_dir):
        r = _post_raw(server_url, (edge_cases_dir / "zero_byte.bin").read_bytes())
        assert r.status_code == 400

    def test_pdf_zero_byte(self, server_url, edge_cases_dir):
        r = _post_pdf(server_url, (edge_cases_dir / "zero_byte.bin").read_bytes())
        assert r.status_code == 400

    def test_pixels_zero_byte(self, server_url):
        r = _post_pixels(server_url, b"", 1, 1, 3)
        assert r.status_code == 400


# --- corrupt / garbage bodies ---------------------------------------------

class TestCorruptInput:
    def test_raw_corrupt_jpeg(self, server_url, edge_cases_dir):
        r = _post_raw(
            server_url,
            (edge_cases_dir / "corrupt_truncated.jpg").read_bytes(),
            content_type="image/jpeg",
        )
        assert r.status_code == 400

    def test_raw_random_garbage(self, server_url, edge_cases_dir):
        r = _post_raw(server_url, (edge_cases_dir / "garbage_random.bin").read_bytes())
        assert r.status_code == 400

    def test_pdf_random_garbage(self, server_url, edge_cases_dir):
        r = _post_pdf(server_url, (edge_cases_dir / "garbage_random.bin").read_bytes())
        assert r.status_code == 400


# --- degenerate images (tiny / huge) --------------------------------------

class TestDegenerateImages:
    def test_one_pixel_png(self, server_url, edge_cases_dir):
        r = _post_raw(server_url, (edge_cases_dir / "one_pixel.png").read_bytes())
        assert r.status_code == 200
        assert r.json().get("results") == []

    def test_4k_image(self, server_url, edge_cases_dir):
        r = _post_raw(
            server_url,
            (edge_cases_dir / "4k_text.png").read_bytes(),
            timeout=60,
        )
        assert r.status_code == 200
        assert len(r.json().get("results", [])) > 0


# --- degenerate PDFs -------------------------------------------------------

@pytest.mark.parametrize("mode", ["ocr", "geometric", "auto", "auto_verified"])
class TestDegeneratePdfs:
    def test_whitespace_only_pdf(self, server_url, edge_cases_dir, mode):
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "whitespace_only.pdf").read_bytes(),
            mode=mode,
        )
        assert r.status_code == 200
        data = r.json()
        assert "pages" in data
        # Zero or empty results are both fine.

    def test_no_text_layer_pdf(self, server_url, edge_cases_dir, mode):
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "no_text_layer.pdf").read_bytes(),
            mode=mode,
        )
        assert r.status_code == 200
        data = r.json()
        assert "pages" in data

    def test_rotated_90_pdf(self, server_url, edge_cases_dir, mode):
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "rotated_90.pdf").read_bytes(),
            mode=mode,
        )
        assert r.status_code == 200
        assert len(r.json()["pages"]) == 1

    def test_cropbox_offset_pdf(self, server_url, edge_cases_dir, mode):
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "cropbox_offset.pdf").read_bytes(),
            mode=mode,
        )
        assert r.status_code == 200
        assert len(r.json()["pages"]) == 1


class TestPasswordProtectedPdf:
    def test_password_protected_returns_error(self, server_url, edge_cases_dir):
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "password_protected.pdf").read_bytes(),
        )
        assert r.status_code in (400, 422, 500), (
            f"expected error for encrypted PDF, got {r.status_code}"
        )


# --- large PDF -------------------------------------------------------------

class TestLargePdf:
    @pytest.mark.parametrize("mode", ["geometric", "auto"])
    def test_500_page_pdf(self, server_url, edge_cases_dir, mode):
        """500-page PDF on text-layer modes (fast); mode=ocr skipped for runtime."""
        r = _post_pdf(
            server_url,
            (edge_cases_dir / "pdf_500_pages.pdf").read_bytes(),
            mode=mode,
            timeout=300,
        )
        assert r.status_code == 200
        data = r.json()
        assert len(data["pages"]) == 500


# --- method and protocol --------------------------------------------------

class TestProtocolEdges:
    def test_ocr_batch_empty_list(self, server_url):
        r = requests.post(f"{server_url}/ocr/batch", json={"images": []}, timeout=10)
        assert r.status_code in (200, 400)

    def test_ocr_batch_wrong_field(self, server_url):
        r = requests.post(f"{server_url}/ocr/batch", json={"wrong": []}, timeout=10)
        assert r.status_code == 400

    def test_unknown_pdf_mode(self, server_url, fixtures_dir):
        pdf = fixtures_dir / "pdf" / "simple_letter.pdf"
        if not pdf.exists():
            pytest.skip()
        r = requests.post(
            f"{server_url}/ocr/pdf?mode=nonsense",
            data=pdf.read_bytes(),
            headers={"Content-Type": "application/pdf"},
            timeout=30,
        )
        # Either 400 or fallback to default — both acceptable, just no crash.
        assert r.status_code in (200, 400)
